#pragma config(Sensor, S2,     sensorLightLSRotate, sensorLightActive)
#pragma config(Sensor, S3,     sensorLightRotate, sensorLightActive)
#pragma config(Sensor, S4,     sensorCubeAttatch, sensorTouch)
#pragma config(Motor,  motorA,          motorRotate,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorPlatform, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorLS,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


///////////////////////////////////////////////////////////



const float tRatioRT = (float)56 / 23;
const float tRatioLS = (float)40 / 8;

const int rotateLimitLightThreshold = 76;
const int LSRotateLightThreshold = 65;

const int ENCODERvAL_LS_BASE = -1830;
const int ENCODERvAL_LS_ARRAY[] = {
    ENCODERvAL_LS_BASE,
    // Below is the increasement value of LS
    0,          // LS1
    -380,       // LS2
    -730,       // LS3
    -1110       // LS4
};



//////////////////////////////////////////////////////////
const int BTN_Gray_Rectangle    = 0;
const int BTN_Right_Arrow       = 1;
const int BTN_Left_Arrow        = 2;
const int BTN_Orange_Square     = 3;

const int STATE_ROTATE_AT_INIT      = 0;
const int STATE_ROTATE_AT_BEHIND    = 1;
const int STATE_ROTATE_AT_LEAN      = 2;
const int STATE_ROTATE_AT_ELSE      = 3;

const char STATE_PLATFORM_AT_BOTTOM_LIMIT = 0;
const char STATE_PLATFORM_AT_LS1          = 101;
const char STATE_PLATFORM_AT_LS2          = 102;
const char STATE_PLATFORM_AT_LS3          = 103;
const char STATE_PLATFORM_AT_LS4          = 104;